<a href="https://colab.research.google.com/github/danlamberg/Atividade-Data-Science/blob/DevDaniel/Trabalho_Bimestral.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Trabalho Bimestral

ALUNO: DANIEL DE OLIVEIRA LAMBERG

ALUNO: DIOGO VARONI DE MOURA

RM: 12210919

RM: 13135759

TURMA: Data Science - Osório Sala 404 - QUA - 19:00 - 21:40

Aplicar as visualizações e conceitos discutimos nas últimas aulas.


Link do Dataset - 2022_OrcamentoDespesa - link geral - https://www.portaltransparencia.gov.br/download-de-dados/orcamento-despesa

Dicionário de Dados - Orçamento da Despesa: https://www.portaldatransparencia.gov.br/pagina-interna/603417-dicionario-de-dados-orcamento-da-despesa

### **Importando Pandas e bibliotecas:**

In [229]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

sns.set()

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Conectando ao Google Drive:

In [230]:
%matplotlib inline

df = pd.read_csv('/content/drive/MyDrive/BSI/DATA SCIENCE/Colab Notebooks/Bck_Trabalho/2022_OrcamentoDespesa.zip.csv', 
                 sep=';', encoding='latin-1')

Visualizando o que está no Data Frame, visualização das primeiras linhas:

In [231]:
df.head()

,EXERCÍCIO,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO SUBORDINADO,NOME ÓRGÃO SUBORDINADO,...,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$)
0,2022,20000,Presidência da República,20101,Presidência da República,...,Equipamentos e Material Permanente,"13480668,50","13480668,50","7246467,68","4713795,18"
1,2022,20000,Presidência da República,20101,Presidência da República,...,Serviços de Tecnologia da Informação e Comunic...,"731282,02","731282,02","168630,78","0,00"
2,2022,20000,Presidência da República,20101,Presidência da República,...,Não informado,"20709758,00","0,00","0,00","0,00"
3,2022,20000,Presidência da República,20101,Presidência da República,...,Obras e Instalações,"12520280,50","12520280,50","1475909,94","773852,43"
4,2022,20000,Presidência da República,20101,Presidência da República,...,Não informado,"-11877454,00","0,00","0,00","0,00"

Método de rotação do Data Frame:

In [232]:
df.T

,0,1,2,3,4,...,22150,22151,22152,22153,22154
EXERCÍCIO,2022,2022,2022,2022,2022,...,2022,2022,2022,2022,2022
CÓDIGO ÓRGÃO SUPERIOR,20000,20000,20000,20000,20000,...,81000,81000,81000,81000,81000
NOME ÓRGÃO SUPERIOR,Presidência da República,Presidência da República,Presidência da República,Presidência da República,Presidência da República,...,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Humanos"
CÓDIGO ÓRGÃO SUBORDINADO,20101,20101,20101,20101,20101,...,81000,81000,81000,81000,81000
NOME ÓRGÃO SUBORDINADO,Presidência da República,Presidência da República,Presidência da República,Presidência da República,Presidência da República,...,"Ministério da Mulher, Família e Direitos Human...","Ministério da Mulher, Família e Direitos Human...","Ministério da Mulher, Família e Direitos Human...","Ministério da Mulher, Família e Direitos Human...","Ministério da Mulher, Família e Direitos Human..."
CÓDIGO UNIDADE ORÇAMENTÁRIA,20101,20101,20101,20101,20101,...,81101,81101,81101,81101,81101
NOME UNIDADE ORÇAMENTÁRIA,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,PRESIDENCIA DA REPUBLICA,...,MINISTERIO DOS DIREITOS HUMANOS - MDH,MINISTERIO DOS DIREITOS HUMANOS - MDH,MINISTERIO DOS DIREITOS HUMANOS - MDH,MINISTERIO DOS DIREITOS HUMANOS - MDH,MINISTERIO DOS DIREITOS HUMANOS - MDH
CÓDIGO FUNÇÃO,4,4,4,4,4,...,14,14,14,14,99
NOME FUNÇÃO,Administração,Administração,Administração,Administração,Administração,...,Direitos da cidadania,Direitos da cidadania,Direitos da cidadania,Direitos da cidadania,Reserva de contingência
CÓDIGO SUBFUNÇÃO,122,122,122,122,122,...,422,422,422,422,999
NOME SUBFUNÇÃO,Administração geral,Administração geral,Administração geral,Administração geral,Administração geral,...,"Direitos individuais, coletivos e difusos","Direitos individuais, coletivos e difusos","Direitos individuais, coletivos e difusos","Direitos individuais, coletivos e difusos",Reserva de contingência
CÓDIGO PROGRAMA ORÇAMENTÁRIO,32,32,32,32,32,...,5034,5034,5034,5034,999
NOME PROGRAMA ORÇAMENTÁRIO,PROGRAMA DE GESTAO E MANUTENCAO DO PODER EXECU...,PROGRAMA DE GESTAO E MANUTENCAO DO PODER EXECU...,PROGRAMA DE GESTAO E MANUTENCAO DO PODER EXECU...,PROGRAMA DE GESTAO E MANUTENCAO DO PODER EXECU...,PROGRAMA DE GESTAO E MANUTENCAO DO PODER EXECU...,...,"PROTECAO A VIDA, FORTALECIMENTO DA FAMILIA, PR...","PROTECAO A VIDA, FORTALECIMENTO DA FAMILIA, PR...","PROTECAO A VIDA, FORTALECIMENTO DA FAMILIA, PR...","PROTECAO A VIDA, FORTALECIMENTO DA FAMILIA, PR...",RESERVA DE CONTINGENCIA
CÓDIGO AÇÃO,15XF,15XF,15XF,15XF,15XF,...,218B,218B,218B,218B,0Z00
NOME AÇÃO,MODERNIZACAO DA INFRAESTRUTURA DA PRESIDENCIA ...,MODERNIZACAO DA INFRAESTRUTURA DA PRESIDENCIA ...,MODERNIZACAO DA INFRAESTRUTURA DA PRESIDENCIA ...,MODERNIZACAO DA INFRAESTRUTURA DA PRESIDENCIA ...,MODERNIZACAO DA INFRAESTRUTURA DA PRESIDENCIA ...,...,POLITICAS DE IGUALDADE E ENFRENTAMENTO A VIOLE...,POLITICAS DE IGUALDADE E ENFRENTAMENTO A VIOLE...,POLITICAS DE IGUALDADE E ENFRENTAMENTO A VIOLE...,POLITICAS DE IGUALDADE E ENFRENTAMENTO A VIOLE...,RESERVA DE CONTINGENCIA - FINANCEIRA
CÓDIGO CATEGORIA ECONÔMICA,4,3,4,4,3,...,3,3,4,3,9
NOME CATEGORIA ECONÔMICA,DESPESAS DE CAPITAL,DESPESAS CORRENTES,DESPESAS DE CAPITAL,DESPESAS DE CAPITAL,DESPESAS CORRENTES,...,DESPESAS CORRENTES,DESPESAS CORRENTES,DESPESAS DE CAPITAL,DESPESAS CORRENTES,RESERVA DE CONTINGENCIA
CÓDIGO GRUPO DE DESPESA,4,3,4,4,3,...,3,3,4,3,9
NOME GRUPO DE DESPESA,Investimentos,Outras Despesas Correntes,Investimentos,Investimentos,Outras Despesas Correntes,...,Outras Despesas Correntes,Outras Despesas Correntes,Investimentos,Outras Despesas Correntes,Reserva de Contingência
CÓDIGO ELEMENTO DE DESPESA,52,40,0,51,0,...,41,41,41,0,0
NOME ELEMENTO DE DESPESA,Equipamentos e Material Permanente,Serviços de Tecnologia da Informação e Comunic...,Não informado,Obras e Instalações,Não informado,...,Contribuições,Contribuições,Contribuições,Não informado,Não informado
ORÇAMENTO INICIAL (R$),"13480668,50","731282,02","20709758,00","12520280,50","-11877454,00",...,"250000,00","440000,00","160000,00","200000,00","405386427,00"
ORÇAMENTO ATUALIZADO (R$),"13480668,50","731282,02","0,00","12520280,50","0,00",...,"250000,00","440000,00","160000,00","500000,00","405386427,00"
ORÇAMENTO EMPENHADO (R$),"7246467,68","168630,78","0,00","1475909,94","0,00",...,"150000,00","440000,00","160000,00","0,00","0,00"
ORÇAMENTO REALIZADO (R$),"4713795,18","0,00","0,00","773852,43","0,00",...,"0,00","0,00","0,00","0,00","0,00"

Quantidade de colunas e linhas:

In [233]:
df.shape

(22155, 25)

Tamanho do Data Frame, usando a função `len()`:

In [234]:
print("Tamanho do Data Frame: ", len(df))

Tamanho do Data Frame:  22155

Método para verificação se o Pandas realizou a leitura correta dos valores nas colunas:

In [235]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22155 entries, 0 to 22154
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EXERCÍCIO                     22155 non-null  int64
 1   CÓDIGO ÓRGÃO SUPERIOR         22155 non-null  int64
 2   NOME ÓRGÃO SUPERIOR           22155 non-null  object
 3   CÓDIGO ÓRGÃO SUBORDINADO      22155 non-null  int64
 4   NOME ÓRGÃO SUBORDINADO        22155 non-null  object
 5   CÓDIGO UNIDADE ORÇAMENTÁRIA   22155 non-null  int64
 6   NOME UNIDADE ORÇAMENTÁRIA     22155 non-null  object
 7   CÓDIGO FUNÇÃO                 22155 non-null  int64
 8   NOME FUNÇÃO                   22155 non-null  object
 9   CÓDIGO SUBFUNÇÃO              22155 non-null  int64
 10  NOME SUBFUNÇÃO                22155 non-null  object
 11  CÓDIGO PROGRAMA ORÇAMENTÁRIO  22155 non-null  int64
 12  NOME PROGRAMA ORÇAMENTÁRIO    22155 non-null  object
 13  CÓDIGO AÇÃO                   22155 non-null  object
 14  NOME AÇÃO                     22155 non-null  object
 15  CÓDIGO CATEGORIA ECONÔMICA    22155 non-null  int64
 16  NOME CATEGORIA ECONÔMICA      22155 non-null  object
 17  CÓDIGO GRUPO DE DESPESA       22155 non-null  int64
 18  NOME GRUPO DE DESPESA         22155 non-null  object
 19  CÓDIGO ELEMENTO DE DESPESA    22155 non-null  int64
 20  NOME ELEMENTO DE DESPESA      22155 non-null  object
 21  ORÇAMENTO INICIAL (R$)        22155 non-null  object
 22  ORÇAMENTO ATUALIZADO (R$)     22155 non-null  object
 23  ORÇAMENTO EMPENHADO (R$)      22155 non-null  object
 24  ORÇAMENTO REALIZADO (R$)      22155 non-null  object
dtypes: int64(10), object(15)
memory usage: 4.2+ MB

## Localizando e tratando valores inválidos:

Exibindo todas as linhas com valores em branco (*NaN*):

In [236]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [EXERCÍCIO, CÓDIGO ÓRGÃO SUPERIOR, NOME ÓRGÃO SUPERIOR, CÓDIGO ÓRGÃO SUBORDINADO, NOME ÓRGÃO SUBORDINADO, CÓDIGO UNIDADE ORÇAMENTÁRIA, NOME UNIDADE ORÇAMENTÁRIA, CÓDIGO FUNÇÃO, NOME FUNÇÃO, CÓDIGO SUBFUNÇÃO, NOME SUBFUNÇÃO, CÓDIGO PROGRAMA ORÇAMENTÁRIO, NOME PROGRAMA ORÇAMENTÁRIO, CÓDIGO AÇÃO, NOME AÇÃO, CÓDIGO CATEGORIA ECONÔMICA, NOME CATEGORIA ECONÔMICA, CÓDIGO GRUPO DE DESPESA, NOME GRUPO DE DESPESA, CÓDIGO ELEMENTO DE DESPESA, NOME ELEMENTO DE DESPESA, ORÇAMENTO INICIAL (R$), ORÇAMENTO ATUALIZADO (R$), ORÇAMENTO EMPENHADO (R$), ORÇAMENTO REALIZADO (R$)]
Index: []

[0 rows x 25 columns]

In [237]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22155 entries, 0 to 22154
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EXERCÍCIO                     22155 non-null  int64
 1   CÓDIGO ÓRGÃO SUPERIOR         22155 non-null  int64
 2   NOME ÓRGÃO SUPERIOR           22155 non-null  object
 3   CÓDIGO ÓRGÃO SUBORDINADO      22155 non-null  int64
 4   NOME ÓRGÃO SUBORDINADO        22155 non-null  object
 5   CÓDIGO UNIDADE ORÇAMENTÁRIA   22155 non-null  int64
 6   NOME UNIDADE ORÇAMENTÁRIA     22155 non-null  object
 7   CÓDIGO FUNÇÃO                 22155 non-null  int64
 8   NOME FUNÇÃO                   22155 non-null  object
 9   CÓDIGO SUBFUNÇÃO              22155 non-null  int64
 10  NOME SUBFUNÇÃO                22155 non-null  object
 11  CÓDIGO PROGRAMA ORÇAMENTÁRIO  22155 non-null  int64
 12  NOME PROGRAMA ORÇAMENTÁRIO    22155 non-null  object
 13  CÓDIGO AÇÃO                   22155 non-null  object
 14  NOME AÇÃO                     22155 non-null  object
 15  CÓDIGO CATEGORIA ECONÔMICA    22155 non-null  int64
 16  NOME CATEGORIA ECONÔMICA      22155 non-null  object
 17  CÓDIGO GRUPO DE DESPESA       22155 non-null  int64
 18  NOME GRUPO DE DESPESA         22155 non-null  object
 19  CÓDIGO ELEMENTO DE DESPESA    22155 non-null  int64
 20  NOME ELEMENTO DE DESPESA      22155 non-null  object
 21  ORÇAMENTO INICIAL (R$)        22155 non-null  object
 22  ORÇAMENTO ATUALIZADO (R$)     22155 non-null  object
 23  ORÇAMENTO EMPENHADO (R$)      22155 non-null  object
 24  ORÇAMENTO REALIZADO (R$)      22155 non-null  object
dtypes: int64(10), object(15)
memory usage: 4.2+ MB

Deletando colunas que não serão importantes na análise dos dados:

In [238]:
df = df.drop(columns=['EXERCÍCIO', 'CÓDIGO ÓRGÃO SUPERIOR','CÓDIGO ÓRGÃO SUBORDINADO', 'CÓDIGO UNIDADE ORÇAMENTÁRIA','CÓDIGO FUNÇÃO','CÓDIGO SUBFUNÇÃO',
                      'CÓDIGO PROGRAMA ORÇAMENTÁRIO', 'CÓDIGO AÇÃO', 'CÓDIGO CATEGORIA ECONÔMICA', 'CÓDIGO GRUPO DE DESPESA','CÓDIGO ELEMENTO DE DESPESA'])

In [239]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22155 entries, 0 to 22154
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   NOME ÓRGÃO SUPERIOR         22155 non-null  object
 1   NOME ÓRGÃO SUBORDINADO      22155 non-null  object
 2   NOME UNIDADE ORÇAMENTÁRIA   22155 non-null  object
 3   NOME FUNÇÃO                 22155 non-null  object
 4   NOME SUBFUNÇÃO              22155 non-null  object
 5   NOME PROGRAMA ORÇAMENTÁRIO  22155 non-null  object
 6   NOME AÇÃO                   22155 non-null  object
 7   NOME CATEGORIA ECONÔMICA    22155 non-null  object
 8   NOME GRUPO DE DESPESA       22155 non-null  object
 9   NOME ELEMENTO DE DESPESA    22155 non-null  object
 10  ORÇAMENTO INICIAL (R$)      22155 non-null  object
 11  ORÇAMENTO ATUALIZADO (R$)   22155 non-null  object
 12  ORÇAMENTO EMPENHADO (R$)    22155 non-null  object
 13  ORÇAMENTO REALIZADO (R$)    22155 non-null  object
dtypes: object(14)
memory usage: 2.4+ MB

Exibindo as colunas e os tipos identificados:

In [240]:
colunas = df.columns

print(type(colunas))
colunas

<class 'pandas.core.indexes.base.Index'>

Index(['NOME ÓRGÃO SUPERIOR', 'NOME ÓRGÃO SUBORDINADO',
       'NOME UNIDADE ORÇAMENTÁRIA', 'NOME FUNÇÃO', 'NOME SUBFUNÇÃO',
       'NOME PROGRAMA ORÇAMENTÁRIO', 'NOME AÇÃO', 'NOME CATEGORIA ECONÔMICA',
       'NOME GRUPO DE DESPESA', 'NOME ELEMENTO DE DESPESA',
       'ORÇAMENTO INICIAL (R$)', 'ORÇAMENTO ATUALIZADO (R$)',
       'ORÇAMENTO EMPENHADO (R$)', 'ORÇAMENTO REALIZADO (R$)'],
      dtype='object')

Exemplo de seleção de campos de interesse:

In [241]:
df_aux = df[['NOME ELEMENTO DE DESPESA', 'ORÇAMENTO INICIAL (R$)', 'ORÇAMENTO ATUALIZADO (R$)', 'ORÇAMENTO EMPENHADO (R$)', 'ORÇAMENTO REALIZADO (R$)']]
df_aux

,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$)
0,Equipamentos e Material Permanente,"13480668,50","13480668,50","7246467,68","4713795,18"
1,Serviços de Tecnologia da Informação e Comunic...,"731282,02","731282,02","168630,78","0,00"
2,Não informado,"20709758,00","0,00","0,00","0,00"
3,Obras e Instalações,"12520280,50","12520280,50","1475909,94","773852,43"
4,Não informado,"-11877454,00","0,00","0,00","0,00"
...,...,...,...,...,...
22150,Contribuições,"250000,00","250000,00","150000,00","0,00"
22151,Contribuições,"440000,00","440000,00","440000,00","0,00"
22152,Contribuições,"160000,00","160000,00","160000,00","0,00"
22153,Não informado,"200000,00","500000,00","0,00","0,00"
22154,Não informado,"405386427,00","405386427,00","0,00","0,00"

Exibindo estatísticas do Data Frame com as colunas desejadas:

In [242]:
df.describe()

,NOME ÓRGÃO SUPERIOR,NOME ÓRGÃO SUBORDINADO,NOME UNIDADE ORÇAMENTÁRIA,NOME FUNÇÃO,NOME SUBFUNÇÃO,...,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$)
count,22155,22155,22155,22155,22155,...,22155,22155,22155,22155,22155
unique,21,248,326,27,95,...,71,18905,18303,13392,13649
top,Ministério da Educação,Ministério da Economia - Unidades com vínculo ...,FUNDO NACIONAL DE SAUDE,Educação,Ensino superior,...,Não informado,"1000,00","0,00","0,00","0,00"
freq,9839,676,605,8376,3345,...,4869,281,779,6886,8229

Conversão de valores:

In [243]:
df['ORÇAMENTO INICIAL (R$)'] = df['ORÇAMENTO INICIAL (R$)'].astype(str)
df['ORÇAMENTO INICIAL (R$)'] = df['ORÇAMENTO INICIAL (R$)'].str.replace(',', '.')
df['ORÇAMENTO INICIAL (R$)'] = df['ORÇAMENTO INICIAL (R$)'].astype(float)
df['ORÇAMENTO ATUALIZADO (R$)'] = df['ORÇAMENTO ATUALIZADO (R$)'].astype(str)
df['ORÇAMENTO ATUALIZADO (R$)'] = df['ORÇAMENTO ATUALIZADO (R$)'].str.replace(',', '.')
df['ORÇAMENTO ATUALIZADO (R$)'] = df['ORÇAMENTO ATUALIZADO (R$)'].astype(float)
df['ORÇAMENTO EMPENHADO (R$)'] = df['ORÇAMENTO EMPENHADO (R$)'].astype(str)
df['ORÇAMENTO EMPENHADO (R$)'] = df['ORÇAMENTO EMPENHADO (R$)'].str.replace(',', '.')
df['ORÇAMENTO EMPENHADO (R$)'] = df['ORÇAMENTO EMPENHADO (R$)'].astype(float)
df['ORÇAMENTO REALIZADO (R$)'] = df['ORÇAMENTO REALIZADO (R$)'].astype(str)
df['ORÇAMENTO REALIZADO (R$)'] = df['ORÇAMENTO REALIZADO (R$)'].str.replace(',', '.')
df['ORÇAMENTO REALIZADO (R$)'] = df['ORÇAMENTO REALIZADO (R$)'].astype(float)

In [244]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22155 entries, 0 to 22154
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   NOME ÓRGÃO SUPERIOR         22155 non-null  object
 1   NOME ÓRGÃO SUBORDINADO      22155 non-null  object
 2   NOME UNIDADE ORÇAMENTÁRIA   22155 non-null  object
 3   NOME FUNÇÃO                 22155 non-null  object
 4   NOME SUBFUNÇÃO              22155 non-null  object
 5   NOME PROGRAMA ORÇAMENTÁRIO  22155 non-null  object
 6   NOME AÇÃO                   22155 non-null  object
 7   NOME CATEGORIA ECONÔMICA    22155 non-null  object
 8   NOME GRUPO DE DESPESA       22155 non-null  object
 9   NOME ELEMENTO DE DESPESA    22155 non-null  object
 10  ORÇAMENTO INICIAL (R$)      22155 non-null  float64
 11  ORÇAMENTO ATUALIZADO (R$)   22155 non-null  float64
 12  ORÇAMENTO EMPENHADO (R$)    22155 non-null  float64
 13  ORÇAMENTO REALIZADO (R$)    22155 non-null  float64
dtypes: float64(4), object(10)
memory usage: 2.4+ MB

Somando o Valor **"ORÇAMENTO INICIAL"** com o valor **"ORÇAMENTO EMPENHADO"**:

In [ ]:
df['soma_total'] = df['ORÇAMENTO INICIAL (R$)'] + df['ORÇAMENTO EMPENHADO (R$)']
df

,NOME ÓRGÃO SUPERIOR,NOME ÓRGÃO SUBORDINADO,NOME UNIDADE ORÇAMENTÁRIA,NOME FUNÇÃO,NOME SUBFUNÇÃO,...,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$),soma_total
0,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,"13480668,50","13480668,50","7246467,68","4713795,18","13480668,507246467,68"
1,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,"731282,02","731282,02","168630,78","0,00","731282,02168630,78"
2,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,"20709758,00","0,00","0,00","0,00","20709758,000,00"
3,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,"12520280,50","12520280,50","1475909,94","773852,43","12520280,501475909,94"
4,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,"-11877454,00","0,00","0,00","0,00","-11877454,000,00"
...,...,...,...,...,...,...,...,...,...,...,...
22150,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Direitos da cidadania,"Direitos individuais, coletivos e difusos",...,"250000,00","250000,00","150000,00","0,00","250000,00150000,00"
22151,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Direitos da cidadania,"Direitos individuais, coletivos e difusos",...,"440000,00","440000,00","440000,00","0,00","440000,00440000,00"
22152,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Direitos da cidadania,"Direitos individuais, coletivos e difusos",...,"160000,00","160000,00","160000,00","0,00","160000,00160000,00"
22153,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Direitos da cidadania,"Direitos individuais, coletivos e difusos",...,"200000,00","500000,00","0,00","0,00","200000,000,00"
22154,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Reserva de contingência,Reserva de contingência,...,"405386427,00","405386427,00","0,00","0,00","405386427,000,00"

Renomeando a coluna Soma Total apenas por "TOTAL", tendo como referência o valor "ORÇAMENTO INICIAL " com o valor "ORÇAMENTO REALIZADO":

In [ ]:
df = df.rename(columns={'soma_total': 'TOTAL'})
df_aux = df[['TOTAL']]
df_aux

                       TOTAL
0      13480668,507246467,68
1         731282,02168630,78
2            20709758,000,00
3      12520280,501475909,94
4           -11877454,000,00
...                      ...
22150     250000,00150000,00
22151     440000,00440000,00
22152     160000,00160000,00
22153          200000,000,00
22154       405386427,000,00

[22155 rows x 1 columns]

Removendo a coluna TOTAL:

In [ ]:
df = df.drop(columns=['TOTAL'])

# df.drop(columns=['total'], inplace=True)
df

,NOME ÓRGÃO SUPERIOR,NOME ÓRGÃO SUBORDINADO,NOME UNIDADE ORÇAMENTÁRIA,NOME FUNÇÃO,NOME SUBFUNÇÃO,...,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$)
0,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,Equipamentos e Material Permanente,"13480668,50","13480668,50","7246467,68","4713795,18"
1,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,Serviços de Tecnologia da Informação e Comunic...,"731282,02","731282,02","168630,78","0,00"
2,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,Não informado,"20709758,00","0,00","0,00","0,00"
3,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,Obras e Instalações,"12520280,50","12520280,50","1475909,94","773852,43"
4,Presidência da República,Presidência da República,PRESIDENCIA DA REPUBLICA,Administração,Administração geral,...,Não informado,"-11877454,00","0,00","0,00","0,00"
...,...,...,...,...,...,...,...,...,...,...,...
22150,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Direitos da cidadania,"Direitos individuais, coletivos e difusos",...,Contribuições,"250000,00","250000,00","150000,00","0,00"
22151,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Direitos da cidadania,"Direitos individuais, coletivos e difusos",...,Contribuições,"440000,00","440000,00","440000,00","0,00"
22152,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Direitos da cidadania,"Direitos individuais, coletivos e difusos",...,Contribuições,"160000,00","160000,00","160000,00","0,00"
22153,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Direitos da cidadania,"Direitos individuais, coletivos e difusos",...,Não informado,"200000,00","500000,00","0,00","0,00"
22154,"Ministério da Mulher, Família e Direitos Humanos","Ministério da Mulher, Família e Direitos Human...",MINISTERIO DOS DIREITOS HUMANOS - MDH,Reserva de contingência,Reserva de contingência,...,Não informado,"405386427,00","405386427,00","0,00","0,00"

Maior despesa realizada:

In [ ]:
print("Maior despesa registrada: " + str(df['ORÇAMENTO REALIZADO (R$)'].max()))

Maior despesa registrada: 9999,12

Menor despesa registrada:

In [ ]:
print("Menor despesa registrada: " + str(df['ORÇAMENTO REALIZADO (R$)'].min()))

Menor despesa registrada: 0,00

Selecionando um ÓRGÃO SUBORDINADO:

In [ ]:
df_aux = df.loc[df['NOME ÓRGÃO SUPERIOR'] == 'Ministério do Meio Ambiente']
df_aux

,EXERCÍCIO,NOME ÓRGÃO SUPERIOR,NOME ÓRGÃO SUBORDINADO,NOME UNIDADE ORÇAMENTÁRIA,NOME FUNÇÃO,...,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$)
17643,2022,Ministério do Meio Ambiente,Fundo Nacional do Meio Ambiente,FUNDO NACIONAL DO MEIO AMBIENTE,Gestão ambiental,...,Não informado,"-2434019,64","0,36","0,00","0,00"
17644,2022,Ministério do Meio Ambiente,Fundo Nacional do Meio Ambiente,FUNDO NACIONAL DO MEIO AMBIENTE,Gestão ambiental,...,Rateio pela Participação em Consórcio Público,"2434019,64","2434019,64","0,00","0,00"
17645,2022,Ministério do Meio Ambiente,Fundo Nacional do Meio Ambiente,FUNDO NACIONAL DO MEIO AMBIENTE,Gestão ambiental,...,Não informado,"2434020,00","0,00","0,00","0,00"
17646,2022,Ministério do Meio Ambiente,Instituto Brasileiro do Meio Ambiente e dos Re...,INST.BRAS.DO MEIO AMB.E REC.NAT.RENOVAVEIS,Gestão ambiental,...,Não informado,"381238,80","381238,80","0,00","0,00"
17647,2022,Ministério do Meio Ambiente,Instituto Brasileiro do Meio Ambiente e dos Re...,INST.BRAS.DO MEIO AMB.E REC.NAT.RENOVAVEIS,Gestão ambiental,...,Outros Serviços de Terceiros - Pessoa Jurídica,"33000,00","33000,00","33000,00","4896,13"
...,...,...,...,...,...,...,...,...,...,...,...
18047,2022,Ministério do Meio Ambiente,Instituto Brasileiro do Meio Ambiente e dos Re...,INST.BRAS.DO MEIO AMB.E REC.NAT.RENOVAVEIS,Encargos especiais,...,Pensões Especiais,"152883,00","152883,00","152883,00","116922,04"
18048,2022,Ministério do Meio Ambiente,Fundo Nacional do Meio Ambiente,FUNDO NACIONAL DO MEIO AMBIENTE,Reserva de contingência,...,Não informado,"30369551,00","30369551,00","0,00","0,00"
18049,2022,Ministério do Meio Ambiente,Ministério do Meio Ambiente - Unidades com vín...,MINISTERIO DO MEIO AMBIENTE,Reserva de contingência,...,Não informado,"173767683,00","173767683,00","0,00","0,00"
18050,2022,Ministério do Meio Ambiente,Instituto Chico Mendes de Conservação da Biodi...,INST.CHICO MENDES DE CONSER.DA BIODIVERSIDADE,Reserva de contingência,...,Não informado,"2287552,00","2287552,00","0,00","0,00"
18051,2022,Ministério do Meio Ambiente,Instituto Brasileiro do Meio Ambiente e dos Re...,INST.BRAS.DO MEIO AMB.E REC.NAT.RENOVAVEIS,Reserva de contingência,...,Não informado,"150284621,00","150284621,00","0,00","0,00"

## Amostragem Aleatória Simples

In [ ]:
df_amos_simples = df_aux.sample(frac=0.20)
df_amos_simples

,EXERCÍCIO,NOME ÓRGÃO SUPERIOR,NOME ÓRGÃO SUBORDINADO,NOME UNIDADE ORÇAMENTÁRIA,NOME FUNÇÃO,...,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$)
17719,2022,Ministério do Meio Ambiente,Instituto Brasileiro do Meio Ambiente e dos Re...,INST.BRAS.DO MEIO AMB.E REC.NAT.RENOVAVEIS,Encargos especiais,...,Sentenças Judiciais,"42680645,04","42680645,04","0,00","0,00"
18048,2022,Ministério do Meio Ambiente,Fundo Nacional do Meio Ambiente,FUNDO NACIONAL DO MEIO AMBIENTE,Reserva de contingência,...,Não informado,"30369551,00","30369551,00","0,00","0,00"
17842,2022,Ministério do Meio Ambiente,Ministério do Meio Ambiente - Unidades com vín...,MINISTERIO DO MEIO AMBIENTE,Gestão ambiental,...,Não informado,"632965,00","444025,00","0,00","0,00"
17965,2022,Ministério do Meio Ambiente,Ministério do Meio Ambiente - Unidades com vín...,MINISTERIO DO MEIO AMBIENTE,Gestão ambiental,...,Não informado,"223600,00","440000,00","0,00","0,00"
17987,2022,Ministério do Meio Ambiente,Ministério do Meio Ambiente - Unidades com vín...,MINISTERIO DO MEIO AMBIENTE,Gestão ambiental,...,Diárias - Civil,"71308,33","71308,33","30000,00","21231,23"
...,...,...,...,...,...,...,...,...,...,...,...
17800,2022,Ministério do Meio Ambiente,Instituto Brasileiro do Meio Ambiente e dos Re...,INST.BRAS.DO MEIO AMB.E REC.NAT.RENOVAVEIS,Gestão ambiental,...,Despesas de Exercícios Anteriores,"6457,36","6457,36","6457,36","6457,36"
17658,2022,Ministério do Meio Ambiente,Instituto Brasileiro do Meio Ambiente e dos Re...,INST.BRAS.DO MEIO AMB.E REC.NAT.RENOVAVEIS,Gestão ambiental,...,Locação de Mão-de-Obra,"4991860,24","4991860,24","4982292,20","3517329,00"
17989,2022,Ministério do Meio Ambiente,Ministério do Meio Ambiente - Unidades com vín...,MINISTERIO DO MEIO AMBIENTE,Gestão ambiental,...,Outros Serviços de Terceiros - Pessoa Física,"6804,50","6804,50","0,00","0,00"
17915,2022,Ministério do Meio Ambiente,Instituto Chico Mendes de Conservação da Biodi...,INST.CHICO MENDES DE CONSER.DA BIODIVERSIDADE,Gestão ambiental,...,Contratação por Tempo Determinado,"2914,89","2914,89","2914,89","2914,89"
17830,2022,Ministério do Meio Ambiente,Instituto Chico Mendes de Conservação da Biodi...,INST.CHICO MENDES DE CONSER.DA BIODIVERSIDADE,Gestão ambiental,...,Diárias - Civil,"527060,00","527060,00","527060,00","345538,48"

MODA, MEDIA, MEDIANA